version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redis
    privileged: true  # Add this line for testing

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
